{% set name = "diaspora-stream-octopus" %}
{% set version = "0.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/diaspora-project/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c37c629033eec2136530e7c06b92075ca9641cde5498eb1b8b87b420516d4b42

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.21
    - make
    - pkg-config
  host:
    - diaspora-stream-api >=0.5.1
    - librdkafka
    - util-linux
    - aws-sdk-cpp
    - curl
    - zlib
  run:
    - diaspora-stream-api >=0.5.1
    - librdkafka
    - util-linux
    - aws-sdk-cpp
    - curl
    - zlib

test:
  commands:
    - test -f $PREFIX/include/octopus/Driver.hpp

about:
  home: https://github.com/diaspora-project/diaspora-stream-octopus
  license: MIT
  license_family: MIT
  summary: Octopus implementation of the Diaspora Stream API.
  description: |
    Octopus implementation of the Diaspora Stream API.

extra:
  recipe-maintainers:
    - mdorier
